name: movie_search
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  stacked: 1.9.7
  provider: 5.0.0
  reactive_forms: 9.1.0
  font_awesome_flutter: 8.12.0
  frino_icons: ^1.0.1
  moor: 4.1.0
  sqlite3_flutter_libs: ^0.4.1
  path_provider:
  path:
  ffi: ^1.0.0
  cached_network_image: 2.5.1
  rxdart: ^0.23.1
  intl: 0.17.0
  flutter_cache_manager: ^2.1.2
  device_info: 0.4.2+10
  dio: 4.0.0-beta7
  extended_image: 3.0.0
  easy_dynamic_theme: ^2.0.0
  carousel_slider: ^2.3.1
  dots_indicator: ^1.2.0
  shimmer: ^1.1.2
  package_info: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: 4.1.0
  build_runner:
  flutter_launcher_icons: 0.9.0

flutter_icons:
  image_path: "busqueda.png"
  adaptative_icon_background: "background.png"
  ios: false
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Dosis
      fonts:
      - asset: assets/fonts/Dosis-Bold.ttf
      - asset: assets/fonts/Dosis-Book.ttf
      - asset: assets/fonts/Dosis-ExtraBold.ttf
      - asset: assets/fonts/Dosis-ExtraLight.ttf
      - asset: assets/fonts/Dosis-Light.ttf
      - asset: assets/fonts/Dosis-Medium.ttf
      - asset: assets/fonts/Dosis-SemiBold.ttf
  #     - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
