on:
  push:
#    branches: [ master]
    tags:
    - '*'
name: Build Release
jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: '2.0.1'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --split-per-abi
      #VERSIONING
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #UPLOADING
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          # name: Buscador_${{ steps.semvers.outputs.patch }}_arm64_v8a.apk
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: 1vNQ5N8Uacc76lUNEDNYQwI_4s-aLkJ4d
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          # name: Buscador_${{ steps.semvers.outputs.patch }}_armeabi_v7a.apk
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: 1vNQ5N8Uacc76lUNEDNYQwI_4s-aLkJ4d
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: build/app/outputs/flutter-apk/app-x86_64-release.apk
          # name: Buscador_${{ steps.semvers.outputs.patch }}_x86_64.apk
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: 1vNQ5N8Uacc76lUNEDNYQwI_4s-aLkJ4d