on:
  push:
#    branches: [ master]
#     tags:
#     - 'RELEASE'
name: Send Telegram Message
jobs:

  send-notification:
    name: send default message
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Cuaq! MadafaKa!
